#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 140
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 99
#define ALIAS_COUNT 0
#define TOKEN_COUNT 60
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 6

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_module = 2,
  anon_sym_SLASH = 3,
  anon_sym_type = 4,
  anon_sym_EQ = 5,
  anon_sym_var = 6,
  anon_sym_COLON = 7,
  anon_sym_process = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_end_process = 11,
  anon_sym_COMMA = 12,
  anon_sym_ext = 13,
  anon_sym_pre = 14,
  anon_sym_post = 15,
  anon_sym_wr = 16,
  anon_sym_rd = 17,
  anon_sym_nat = 18,
  anon_sym_nat0 = 19,
  anon_sym_real = 20,
  anon_sym_int = 21,
  anon_sym_bool = 22,
  anon_sym_char = 23,
  anon_sym_string = 24,
  anon_sym_LBRACE = 25,
  anon_sym_RBRACE = 26,
  anon_sym_LT = 27,
  anon_sym_GT = 28,
  anon_sym_set = 29,
  anon_sym_of = 30,
  anon_sym_list = 31,
  anon_sym_map = 32,
  anon_sym_to = 33,
  anon_sym_composed = 34,
  anon_sym_end = 35,
  anon_sym_DASH_GT = 36,
  anon_sym_DASH = 37,
  anon_sym_not = 38,
  anon_sym_STAR = 39,
  anon_sym_div = 40,
  anon_sym_rem = 41,
  anon_sym_mod = 42,
  anon_sym_LT_GT = 43,
  anon_sym_LT_EQ = 44,
  anon_sym_GT_EQ = 45,
  anon_sym_inset = 46,
  anon_sym_notinset = 47,
  anon_sym_and = 48,
  anon_sym_or = 49,
  anon_sym_EQ_GT = 50,
  anon_sym_LT_EQ_GT = 51,
  anon_sym_PLUS = 52,
  sym_int = 53,
  sym_real = 54,
  sym_string = 55,
  sym_char = 56,
  anon_sym_true = 57,
  anon_sym_false = 58,
  sym__semicolon = 59,
  sym_source_file = 60,
  sym_module_definition = 61,
  sym_type_definition = 62,
  sym_type_definition_item = 63,
  sym_variable_definition = 64,
  sym_variable_definition_item = 65,
  sym_process_definition = 66,
  sym_process_definition_item = 67,
  sym_parameter_list = 68,
  sym_parameter_item = 69,
  sym_process_body = 70,
  sym_ext_item = 71,
  sym__type = 72,
  sym_primitive_type = 73,
  sym_enumeration_type = 74,
  sym_enumeration_value = 75,
  sym_set_type = 76,
  sym_list_type = 77,
  sym_map_type = 78,
  sym_composite_type = 79,
  sym__expression = 80,
  sym_expression_list = 81,
  sym__constant_expression = 82,
  sym_list_expression = 83,
  sym_map_expression = 84,
  sym_map_item = 85,
  sym_unary_expression = 86,
  sym_binary_expression = 87,
  sym_bool = 88,
  aux_sym_type_definition_repeat1 = 89,
  aux_sym_variable_definition_repeat1 = 90,
  aux_sym_process_definition_repeat1 = 91,
  aux_sym_parameter_list_repeat1 = 92,
  aux_sym_parameter_item_repeat1 = 93,
  aux_sym_process_body_repeat1 = 94,
  aux_sym_enumeration_type_repeat1 = 95,
  aux_sym_composite_type_repeat1 = 96,
  aux_sym_expression_list_repeat1 = 97,
  aux_sym_map_expression_repeat1 = 98,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_module] = "module",
  [anon_sym_SLASH] = "/",
  [anon_sym_type] = "type",
  [anon_sym_EQ] = "=",
  [anon_sym_var] = "var",
  [anon_sym_COLON] = ":",
  [anon_sym_process] = "process",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_end_process] = "end_process",
  [anon_sym_COMMA] = ",",
  [anon_sym_ext] = "ext",
  [anon_sym_pre] = "pre",
  [anon_sym_post] = "post",
  [anon_sym_wr] = "wr",
  [anon_sym_rd] = "rd",
  [anon_sym_nat] = "nat",
  [anon_sym_nat0] = "nat0",
  [anon_sym_real] = "real",
  [anon_sym_int] = "int",
  [anon_sym_bool] = "bool",
  [anon_sym_char] = "char",
  [anon_sym_string] = "string",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_set] = "set",
  [anon_sym_of] = "of",
  [anon_sym_list] = "list",
  [anon_sym_map] = "map",
  [anon_sym_to] = "to",
  [anon_sym_composed] = "composed",
  [anon_sym_end] = "end",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_DASH] = "-",
  [anon_sym_not] = "not",
  [anon_sym_STAR] = "*",
  [anon_sym_div] = "div",
  [anon_sym_rem] = "rem",
  [anon_sym_mod] = "mod",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_inset] = "inset",
  [anon_sym_notinset] = "notinset",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_LT_EQ_GT] = "<=>",
  [anon_sym_PLUS] = "+",
  [sym_int] = "int",
  [sym_real] = "real",
  [sym_string] = "string",
  [sym_char] = "char",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym__semicolon] = "_semicolon",
  [sym_source_file] = "source_file",
  [sym_module_definition] = "module_definition",
  [sym_type_definition] = "type_definition",
  [sym_type_definition_item] = "type_definition_item",
  [sym_variable_definition] = "variable_definition",
  [sym_variable_definition_item] = "variable_definition_item",
  [sym_process_definition] = "process_definition",
  [sym_process_definition_item] = "process_definition_item",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter_item] = "parameter_item",
  [sym_process_body] = "process_body",
  [sym_ext_item] = "ext_item",
  [sym__type] = "_type",
  [sym_primitive_type] = "primitive_type",
  [sym_enumeration_type] = "enumeration_type",
  [sym_enumeration_value] = "enumeration_value",
  [sym_set_type] = "set_type",
  [sym_list_type] = "list_type",
  [sym_map_type] = "map_type",
  [sym_composite_type] = "composite_type",
  [sym__expression] = "_expression",
  [sym_expression_list] = "expression_list",
  [sym__constant_expression] = "_constant_expression",
  [sym_list_expression] = "list_expression",
  [sym_map_expression] = "map_expression",
  [sym_map_item] = "map_item",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_bool] = "bool",
  [aux_sym_type_definition_repeat1] = "type_definition_repeat1",
  [aux_sym_variable_definition_repeat1] = "variable_definition_repeat1",
  [aux_sym_process_definition_repeat1] = "process_definition_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_parameter_item_repeat1] = "parameter_item_repeat1",
  [aux_sym_process_body_repeat1] = "process_body_repeat1",
  [aux_sym_enumeration_type_repeat1] = "enumeration_type_repeat1",
  [aux_sym_composite_type_repeat1] = "composite_type_repeat1",
  [aux_sym_expression_list_repeat1] = "expression_list_repeat1",
  [aux_sym_map_expression_repeat1] = "map_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_process] = anon_sym_process,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_end_process] = anon_sym_end_process,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_ext] = anon_sym_ext,
  [anon_sym_pre] = anon_sym_pre,
  [anon_sym_post] = anon_sym_post,
  [anon_sym_wr] = anon_sym_wr,
  [anon_sym_rd] = anon_sym_rd,
  [anon_sym_nat] = anon_sym_nat,
  [anon_sym_nat0] = anon_sym_nat0,
  [anon_sym_real] = anon_sym_real,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_list] = anon_sym_list,
  [anon_sym_map] = anon_sym_map,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_composed] = anon_sym_composed,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_div] = anon_sym_div,
  [anon_sym_rem] = anon_sym_rem,
  [anon_sym_mod] = anon_sym_mod,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_inset] = anon_sym_inset,
  [anon_sym_notinset] = anon_sym_notinset,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_LT_EQ_GT] = anon_sym_LT_EQ_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_int] = sym_int,
  [sym_real] = sym_real,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym__semicolon] = sym__semicolon,
  [sym_source_file] = sym_source_file,
  [sym_module_definition] = sym_module_definition,
  [sym_type_definition] = sym_type_definition,
  [sym_type_definition_item] = sym_type_definition_item,
  [sym_variable_definition] = sym_variable_definition,
  [sym_variable_definition_item] = sym_variable_definition_item,
  [sym_process_definition] = sym_process_definition,
  [sym_process_definition_item] = sym_process_definition_item,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter_item] = sym_parameter_item,
  [sym_process_body] = sym_process_body,
  [sym_ext_item] = sym_ext_item,
  [sym__type] = sym__type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_enumeration_type] = sym_enumeration_type,
  [sym_enumeration_value] = sym_enumeration_value,
  [sym_set_type] = sym_set_type,
  [sym_list_type] = sym_list_type,
  [sym_map_type] = sym_map_type,
  [sym_composite_type] = sym_composite_type,
  [sym__expression] = sym__expression,
  [sym_expression_list] = sym_expression_list,
  [sym__constant_expression] = sym__constant_expression,
  [sym_list_expression] = sym_list_expression,
  [sym_map_expression] = sym_map_expression,
  [sym_map_item] = sym_map_item,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_bool] = sym_bool,
  [aux_sym_type_definition_repeat1] = aux_sym_type_definition_repeat1,
  [aux_sym_variable_definition_repeat1] = aux_sym_variable_definition_repeat1,
  [aux_sym_process_definition_repeat1] = aux_sym_process_definition_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_parameter_item_repeat1] = aux_sym_parameter_item_repeat1,
  [aux_sym_process_body_repeat1] = aux_sym_process_body_repeat1,
  [aux_sym_enumeration_type_repeat1] = aux_sym_enumeration_type_repeat1,
  [aux_sym_composite_type_repeat1] = aux_sym_composite_type_repeat1,
  [aux_sym_expression_list_repeat1] = aux_sym_expression_list_repeat1,
  [aux_sym_map_expression_repeat1] = aux_sym_map_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_process] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end_process] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ext] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pre] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_post] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rd] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nat0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_real] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_list] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_composed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_div] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rem] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_notinset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_real] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym__semicolon] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_module_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition_item] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition_item] = {
    .visible = true,
    .named = true,
  },
  [sym_process_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_process_definition_item] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_item] = {
    .visible = true,
    .named = true,
  },
  [sym_process_body] = {
    .visible = true,
    .named = true,
  },
  [sym_ext_item] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_enumeration_type] = {
    .visible = true,
    .named = true,
  },
  [sym_enumeration_value] = {
    .visible = true,
    .named = true,
  },
  [sym_set_type] = {
    .visible = true,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_map_type] = {
    .visible = true,
    .named = true,
  },
  [sym_composite_type] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_list] = {
    .visible = true,
    .named = true,
  },
  [sym__constant_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_list_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_map_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_map_item] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_type_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_process_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_process_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enumeration_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_composite_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_field = 1,
  field_field_type = 2,
  field_filed_name = 3,
  field_key = 4,
  field_module_name = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_field] = "field",
  [field_field_type] = "field_type",
  [field_filed_name] = "filed_name",
  [field_key] = "key",
  [field_module_name] = "module_name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 6},
  [5] = {.index = 12, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_module_name, 1},
  [1] =
    {field_key, 1},
    {field_value, 3},
  [3] =
    {field_field, 2, .inherited = true},
    {field_field_type, 2, .inherited = true},
    {field_filed_name, 2, .inherited = true},
  [6] =
    {field_field, 0, .inherited = true},
    {field_field, 1, .inherited = true},
    {field_field_type, 0, .inherited = true},
    {field_field_type, 1, .inherited = true},
    {field_filed_name, 0, .inherited = true},
    {field_filed_name, 1, .inherited = true},
  [12] =
    {field_field, 1},
    {field_field, 3},
    {field_field_type, 2},
    {field_filed_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '+') ADVANCE(26);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '<') ADVANCE(15);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '>') ADVANCE(16);
      if (lookahead == '{') ADVANCE(13);
      if (lookahead == '}') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '+') ADVANCE(26);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(15);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '>') ADVANCE(16);
      if (lookahead == '}') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(2);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT_EQ_GT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_real);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__semicolon);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'b') ADVANCE(2);
      if (lookahead == 'c') ADVANCE(3);
      if (lookahead == 'd') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(8);
      if (lookahead == 'm') ADVANCE(9);
      if (lookahead == 'n') ADVANCE(10);
      if (lookahead == 'o') ADVANCE(11);
      if (lookahead == 'p') ADVANCE(12);
      if (lookahead == 'r') ADVANCE(13);
      if (lookahead == 's') ADVANCE(14);
      if (lookahead == 't') ADVANCE(15);
      if (lookahead == 'v') ADVANCE(16);
      if (lookahead == 'w') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == 'h') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(23);
      if (lookahead == 'x') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(28);
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(30);
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(32);
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(34);
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(36);
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(38);
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(40);
      if (lookahead == 'r') ADVANCE(41);
      if (lookahead == 'y') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(47);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 22:
      if (lookahead == 'v') ADVANCE(49);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(50);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(53);
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(55);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(56);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(57);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(61);
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_rd);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(63);
      if (lookahead == 'm') ADVANCE(64);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(66);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 41:
      if (lookahead == 'u') ADVANCE(67);
      END_STATE();
    case 42:
      if (lookahead == 'p') ADVANCE(68);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(69);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_wr);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(70);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(71);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(72);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_div);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_end);
      if (lookahead == '_') ADVANCE(73);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_ext);
      END_STATE();
    case 52:
      if (lookahead == 's') ADVANCE(74);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_mod);
      if (lookahead == 'u') ADVANCE(77);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_nat);
      if (lookahead == '0') ADVANCE(78);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_not);
      if (lookahead == 'i') ADVANCE(79);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_pre);
      END_STATE();
    case 62:
      if (lookahead == 'c') ADVANCE(81);
      END_STATE();
    case 63:
      if (lookahead == 'l') ADVANCE(82);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_rem);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 66:
      if (lookahead == 'i') ADVANCE(83);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_char);
      END_STATE();
    case 72:
      if (lookahead == 'o') ADVANCE(86);
      END_STATE();
    case 73:
      if (lookahead == 'p') ADVANCE(87);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(89);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_list);
      END_STATE();
    case 77:
      if (lookahead == 'l') ADVANCE(90);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_nat0);
      END_STATE();
    case 79:
      if (lookahead == 'n') ADVANCE(91);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_post);
      END_STATE();
    case 81:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_real);
      END_STATE();
    case 83:
      if (lookahead == 'n') ADVANCE(93);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 86:
      if (lookahead == 's') ADVANCE(94);
      END_STATE();
    case 87:
      if (lookahead == 'r') ADVANCE(95);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_inset);
      END_STATE();
    case 90:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 91:
      if (lookahead == 's') ADVANCE(97);
      END_STATE();
    case 92:
      if (lookahead == 's') ADVANCE(98);
      END_STATE();
    case 93:
      if (lookahead == 'g') ADVANCE(99);
      END_STATE();
    case 94:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 95:
      if (lookahead == 'o') ADVANCE(101);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 97:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 98:
      if (lookahead == 's') ADVANCE(103);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 100:
      if (lookahead == 'd') ADVANCE(104);
      END_STATE();
    case 101:
      if (lookahead == 'c') ADVANCE(105);
      END_STATE();
    case 102:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_process);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_composed);
      END_STATE();
    case 105:
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_notinset);
      END_STATE();
    case 107:
      if (lookahead == 's') ADVANCE(108);
      END_STATE();
    case 108:
      if (lookahead == 's') ADVANCE(109);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_end_process);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_process] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_end_process] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_ext] = ACTIONS(1),
    [anon_sym_pre] = ACTIONS(1),
    [anon_sym_post] = ACTIONS(1),
    [anon_sym_wr] = ACTIONS(1),
    [anon_sym_rd] = ACTIONS(1),
    [anon_sym_nat] = ACTIONS(1),
    [anon_sym_nat0] = ACTIONS(1),
    [anon_sym_real] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_list] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_composed] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_div] = ACTIONS(1),
    [anon_sym_rem] = ACTIONS(1),
    [anon_sym_mod] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_inset] = ACTIONS(1),
    [anon_sym_notinset] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_LT_EQ_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_real] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym__semicolon] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(139),
    [sym_module_definition] = STATE(42),
    [anon_sym_module] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(7), 5,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_EQ,
    ACTIONS(5), 20,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_end_process,
      anon_sym_COMMA,
      anon_sym_post,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_PLUS,
  [30] = 2,
    ACTIONS(11), 5,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_EQ,
    ACTIONS(9), 20,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_end_process,
      anon_sym_COMMA,
      anon_sym_post,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_PLUS,
  [60] = 4,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(15), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
    ACTIONS(17), 7,
      anon_sym_RPAREN,
      anon_sym_end_process,
      anon_sym_COMMA,
      anon_sym_post,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
      anon_sym_PLUS,
    ACTIONS(13), 13,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
  [94] = 2,
    ACTIONS(19), 5,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_EQ,
    ACTIONS(17), 20,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_end_process,
      anon_sym_COMMA,
      anon_sym_post,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_PLUS,
  [124] = 2,
    ACTIONS(23), 5,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_EQ,
    ACTIONS(21), 20,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_end_process,
      anon_sym_COMMA,
      anon_sym_post,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_PLUS,
  [154] = 2,
    ACTIONS(27), 5,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_EQ,
    ACTIONS(25), 20,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_end_process,
      anon_sym_COMMA,
      anon_sym_post,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_PLUS,
  [184] = 2,
    ACTIONS(31), 5,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_EQ,
    ACTIONS(29), 20,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_end_process,
      anon_sym_COMMA,
      anon_sym_post,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_PLUS,
  [214] = 2,
    ACTIONS(35), 5,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_EQ,
    ACTIONS(33), 20,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_end_process,
      anon_sym_COMMA,
      anon_sym_post,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_PLUS,
  [244] = 2,
    ACTIONS(39), 5,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_EQ,
    ACTIONS(37), 20,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      anon_sym_end_process,
      anon_sym_COMMA,
      anon_sym_post,
      anon_sym_RBRACE,
      anon_sym_DASH_GT,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_PLUS,
  [274] = 8,
    ACTIONS(41), 1,
      anon_sym_COMMA,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(49), 1,
      anon_sym_PLUS,
    STATE(86), 1,
      aux_sym_expression_list_repeat1,
    ACTIONS(15), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
    ACTIONS(13), 13,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
  [314] = 11,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    ACTIONS(59), 1,
      anon_sym_DASH_GT,
    STATE(76), 1,
      sym_map_item,
    STATE(109), 1,
      sym_expression_list,
    ACTIONS(51), 2,
      sym_int,
      sym_identifier,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(63), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(11), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [359] = 4,
    ACTIONS(49), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(67), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(15), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
    ACTIONS(13), 13,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
  [389] = 4,
    ACTIONS(49), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(69), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(15), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
    ACTIONS(13), 13,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
  [419] = 8,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_set,
    ACTIONS(79), 1,
      anon_sym_list,
    ACTIONS(81), 1,
      anon_sym_map,
    ACTIONS(83), 1,
      anon_sym_composed,
    ACTIONS(73), 7,
      anon_sym_nat,
      anon_sym_nat0,
      anon_sym_real,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_string,
    STATE(74), 7,
      sym__type,
      sym_primitive_type,
      sym_enumeration_type,
      sym_set_type,
      sym_list_type,
      sym_map_type,
      sym_composite_type,
  [456] = 5,
    ACTIONS(45), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_DASH,
    ACTIONS(49), 1,
      anon_sym_PLUS,
    ACTIONS(15), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
    ACTIONS(13), 13,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
  [487] = 8,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_set,
    ACTIONS(79), 1,
      anon_sym_list,
    ACTIONS(81), 1,
      anon_sym_map,
    ACTIONS(83), 1,
      anon_sym_composed,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(73), 7,
      anon_sym_nat,
      anon_sym_nat0,
      anon_sym_real,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_string,
    STATE(47), 7,
      sym__type,
      sym_primitive_type,
      sym_enumeration_type,
      sym_set_type,
      sym_list_type,
      sym_map_type,
      sym_composite_type,
  [524] = 4,
    ACTIONS(87), 1,
      anon_sym_end_process,
    ACTIONS(49), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(15), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
    ACTIONS(13), 13,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
  [553] = 8,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_set,
    ACTIONS(79), 1,
      anon_sym_list,
    ACTIONS(81), 1,
      anon_sym_map,
    ACTIONS(83), 1,
      anon_sym_composed,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(73), 7,
      anon_sym_nat,
      anon_sym_nat0,
      anon_sym_real,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_string,
    STATE(48), 7,
      sym__type,
      sym_primitive_type,
      sym_enumeration_type,
      sym_set_type,
      sym_list_type,
      sym_map_type,
      sym_composite_type,
  [590] = 4,
    ACTIONS(91), 1,
      anon_sym_post,
    ACTIONS(49), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(15), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
    ACTIONS(13), 13,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
  [619] = 8,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_set,
    ACTIONS(79), 1,
      anon_sym_list,
    ACTIONS(81), 1,
      anon_sym_map,
    ACTIONS(83), 1,
      anon_sym_composed,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(73), 7,
      anon_sym_nat,
      anon_sym_nat0,
      anon_sym_real,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_string,
    STATE(112), 7,
      sym__type,
      sym_primitive_type,
      sym_enumeration_type,
      sym_set_type,
      sym_list_type,
      sym_map_type,
      sym_composite_type,
  [656] = 4,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(49), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(15), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
    ACTIONS(13), 13,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
  [685] = 8,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_set,
    ACTIONS(79), 1,
      anon_sym_list,
    ACTIONS(81), 1,
      anon_sym_map,
    ACTIONS(83), 1,
      anon_sym_composed,
    ACTIONS(97), 1,
      sym_identifier,
    ACTIONS(73), 7,
      anon_sym_nat,
      anon_sym_nat0,
      anon_sym_real,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_string,
    STATE(67), 7,
      sym__type,
      sym_primitive_type,
      sym_enumeration_type,
      sym_set_type,
      sym_list_type,
      sym_map_type,
      sym_composite_type,
  [722] = 8,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_set,
    ACTIONS(79), 1,
      anon_sym_list,
    ACTIONS(81), 1,
      anon_sym_map,
    ACTIONS(83), 1,
      anon_sym_composed,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(73), 7,
      anon_sym_nat,
      anon_sym_nat0,
      anon_sym_real,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_string,
    STATE(126), 7,
      sym__type,
      sym_primitive_type,
      sym_enumeration_type,
      sym_set_type,
      sym_list_type,
      sym_map_type,
      sym_composite_type,
  [759] = 8,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_set,
    ACTIONS(79), 1,
      anon_sym_list,
    ACTIONS(81), 1,
      anon_sym_map,
    ACTIONS(83), 1,
      anon_sym_composed,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(73), 7,
      anon_sym_nat,
      anon_sym_nat0,
      anon_sym_real,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_string,
    STATE(93), 7,
      sym__type,
      sym_primitive_type,
      sym_enumeration_type,
      sym_set_type,
      sym_list_type,
      sym_map_type,
      sym_composite_type,
  [796] = 8,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_set,
    ACTIONS(79), 1,
      anon_sym_list,
    ACTIONS(81), 1,
      anon_sym_map,
    ACTIONS(83), 1,
      anon_sym_composed,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(73), 7,
      anon_sym_nat,
      anon_sym_nat0,
      anon_sym_real,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_string,
    STATE(125), 7,
      sym__type,
      sym_primitive_type,
      sym_enumeration_type,
      sym_set_type,
      sym_list_type,
      sym_map_type,
      sym_composite_type,
  [833] = 4,
    ACTIONS(105), 1,
      anon_sym_end_process,
    ACTIONS(49), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(15), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
    ACTIONS(13), 13,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
  [862] = 4,
    ACTIONS(107), 1,
      anon_sym_post,
    ACTIONS(49), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(15), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
    ACTIONS(13), 13,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_div,
      anon_sym_rem,
      anon_sym_mod,
      anon_sym_LT_GT,
      anon_sym_GT_EQ,
      anon_sym_inset,
      anon_sym_notinset,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
  [891] = 8,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_set,
    ACTIONS(79), 1,
      anon_sym_list,
    ACTIONS(81), 1,
      anon_sym_map,
    ACTIONS(83), 1,
      anon_sym_composed,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(73), 7,
      anon_sym_nat,
      anon_sym_nat0,
      anon_sym_real,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_string,
    STATE(122), 7,
      sym__type,
      sym_primitive_type,
      sym_enumeration_type,
      sym_set_type,
      sym_list_type,
      sym_map_type,
      sym_composite_type,
  [928] = 8,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_set,
    ACTIONS(79), 1,
      anon_sym_list,
    ACTIONS(81), 1,
      anon_sym_map,
    ACTIONS(83), 1,
      anon_sym_composed,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(73), 7,
      anon_sym_nat,
      anon_sym_nat0,
      anon_sym_real,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_string,
    STATE(43), 7,
      sym__type,
      sym_primitive_type,
      sym_enumeration_type,
      sym_set_type,
      sym_list_type,
      sym_map_type,
      sym_composite_type,
  [965] = 8,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    STATE(99), 1,
      sym_map_item,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(113), 2,
      sym_int,
      sym_identifier,
    ACTIONS(115), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(16), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1001] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(117), 2,
      sym_int,
      sym_identifier,
    ACTIONS(119), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(22), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1034] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(121), 2,
      sym_int,
      sym_identifier,
    ACTIONS(123), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(28), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1067] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(125), 2,
      sym_int,
      sym_identifier,
    ACTIONS(127), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(13), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1100] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(129), 2,
      sym_int,
      sym_identifier,
    ACTIONS(131), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(4), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1133] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(133), 2,
      sym_int,
      sym_identifier,
    ACTIONS(135), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(18), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1166] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(137), 2,
      sym_int,
      sym_identifier,
    ACTIONS(139), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(14), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1199] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(141), 2,
      sym_int,
      sym_identifier,
    ACTIONS(143), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(27), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1232] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(145), 2,
      sym_int,
      sym_identifier,
    ACTIONS(147), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(2), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1265] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(149), 2,
      sym_int,
      sym_identifier,
    ACTIONS(151), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(5), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1298] = 7,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_not,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(153), 2,
      sym_int,
      sym_identifier,
    ACTIONS(155), 3,
      sym_real,
      sym_string,
      sym_char,
    STATE(20), 7,
      sym__expression,
      sym__constant_expression,
      sym_list_expression,
      sym_map_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_bool,
  [1331] = 8,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 1,
      anon_sym_type,
    ACTIONS(161), 1,
      anon_sym_var,
    ACTIONS(163), 1,
      anon_sym_process,
    STATE(51), 1,
      sym_type_definition,
    STATE(56), 1,
      sym_variable_definition,
    STATE(137), 1,
      sym_process_definition,
    STATE(68), 2,
      sym_process_definition_item,
      aux_sym_process_definition_repeat1,
  [1357] = 1,
    ACTIONS(165), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
      anon_sym_wr,
      anon_sym_rd,
      anon_sym_to,
      sym__semicolon,
  [1368] = 1,
    ACTIONS(167), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
      anon_sym_wr,
      anon_sym_rd,
      anon_sym_to,
      sym__semicolon,
  [1379] = 1,
    ACTIONS(169), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
      anon_sym_wr,
      anon_sym_rd,
      anon_sym_to,
      sym__semicolon,
  [1390] = 1,
    ACTIONS(171), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
      anon_sym_wr,
      anon_sym_rd,
      anon_sym_to,
      sym__semicolon,
  [1401] = 1,
    ACTIONS(173), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
      anon_sym_wr,
      anon_sym_rd,
      anon_sym_to,
      sym__semicolon,
  [1412] = 1,
    ACTIONS(175), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
      anon_sym_wr,
      anon_sym_rd,
      anon_sym_to,
      sym__semicolon,
  [1423] = 1,
    ACTIONS(177), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
      anon_sym_wr,
      anon_sym_rd,
      anon_sym_to,
      sym__semicolon,
  [1434] = 1,
    ACTIONS(179), 8,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
      anon_sym_wr,
      anon_sym_rd,
      anon_sym_to,
      sym__semicolon,
  [1445] = 6,
    ACTIONS(161), 1,
      anon_sym_var,
    ACTIONS(163), 1,
      anon_sym_process,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    STATE(61), 1,
      sym_variable_definition,
    STATE(132), 1,
      sym_process_definition,
    STATE(68), 2,
      sym_process_definition_item,
      aux_sym_process_definition_repeat1,
  [1465] = 6,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(185), 1,
      anon_sym_ext,
    ACTIONS(187), 1,
      anon_sym_pre,
    STATE(62), 1,
      sym_parameter_item,
    STATE(82), 1,
      sym_parameter_list,
    STATE(110), 1,
      sym_process_body,
  [1484] = 4,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    ACTIONS(191), 1,
      sym_identifier,
    ACTIONS(193), 2,
      anon_sym_var,
      anon_sym_process,
    STATE(54), 2,
      sym_type_definition_item,
      aux_sym_type_definition_repeat1,
  [1499] = 4,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
    ACTIONS(197), 1,
      sym_identifier,
    ACTIONS(200), 2,
      anon_sym_var,
      anon_sym_process,
    STATE(54), 2,
      sym_type_definition_item,
      aux_sym_type_definition_repeat1,
  [1514] = 6,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(185), 1,
      anon_sym_ext,
    ACTIONS(187), 1,
      anon_sym_pre,
    STATE(62), 1,
      sym_parameter_item,
    STATE(90), 1,
      sym_parameter_list,
    STATE(121), 1,
      sym_process_body,
  [1533] = 4,
    ACTIONS(163), 1,
      anon_sym_process,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    STATE(132), 1,
      sym_process_definition,
    STATE(68), 2,
      sym_process_definition_item,
      aux_sym_process_definition_repeat1,
  [1547] = 3,
    ACTIONS(202), 1,
      anon_sym_pre,
    ACTIONS(204), 2,
      anon_sym_wr,
      anon_sym_rd,
    STATE(57), 2,
      sym_ext_item,
      aux_sym_process_body_repeat1,
  [1559] = 3,
    ACTIONS(207), 1,
      anon_sym_pre,
    ACTIONS(209), 2,
      anon_sym_wr,
      anon_sym_rd,
    STATE(57), 2,
      sym_ext_item,
      aux_sym_process_body_repeat1,
  [1571] = 3,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(211), 3,
      anon_sym_RPAREN,
      anon_sym_ext,
      anon_sym_pre,
  [1583] = 4,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
    ACTIONS(217), 1,
      sym_identifier,
    ACTIONS(219), 1,
      anon_sym_process,
    STATE(63), 2,
      sym_variable_definition_item,
      aux_sym_variable_definition_repeat1,
  [1597] = 4,
    ACTIONS(163), 1,
      anon_sym_process,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
    STATE(130), 1,
      sym_process_definition,
    STATE(68), 2,
      sym_process_definition_item,
      aux_sym_process_definition_repeat1,
  [1611] = 3,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(223), 3,
      anon_sym_RPAREN,
      anon_sym_ext,
      anon_sym_pre,
  [1623] = 4,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
    ACTIONS(227), 1,
      sym_identifier,
    ACTIONS(230), 1,
      anon_sym_process,
    STATE(63), 2,
      sym_variable_definition_item,
      aux_sym_variable_definition_repeat1,
  [1637] = 3,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(232), 3,
      anon_sym_RPAREN,
      anon_sym_ext,
      anon_sym_pre,
  [1649] = 2,
    ACTIONS(209), 2,
      anon_sym_wr,
      anon_sym_rd,
    STATE(58), 2,
      sym_ext_item,
      aux_sym_process_body_repeat1,
  [1658] = 2,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
    ACTIONS(239), 3,
      anon_sym_var,
      anon_sym_process,
      sym_identifier,
  [1667] = 1,
    ACTIONS(241), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
  [1674] = 3,
    ACTIONS(163), 1,
      anon_sym_process,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
    STATE(70), 2,
      sym_process_definition_item,
      aux_sym_process_definition_repeat1,
  [1685] = 1,
    ACTIONS(245), 4,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_var,
      anon_sym_process,
  [1692] = 3,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
    ACTIONS(249), 1,
      anon_sym_process,
    STATE(70), 2,
      sym_process_definition_item,
      aux_sym_process_definition_repeat1,
  [1703] = 4,
    ACTIONS(252), 1,
      sym_identifier,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      sym_parameter_item,
    STATE(124), 1,
      sym_parameter_list,
  [1716] = 1,
    ACTIONS(256), 4,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_var,
      anon_sym_process,
  [1723] = 1,
    ACTIONS(232), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
  [1730] = 1,
    ACTIONS(258), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_ext,
      anon_sym_pre,
  [1737] = 3,
    ACTIONS(260), 1,
      anon_sym_COLON,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    STATE(94), 1,
      aux_sym_parameter_item_repeat1,
  [1747] = 3,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      aux_sym_map_expression_repeat1,
  [1757] = 2,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
    ACTIONS(270), 2,
      anon_sym_process,
      sym_identifier,
  [1765] = 3,
    ACTIONS(272), 1,
      sym_identifier,
    ACTIONS(274), 1,
      anon_sym_end,
    STATE(89), 1,
      aux_sym_composite_type_repeat1,
  [1775] = 2,
    ACTIONS(276), 1,
      sym_identifier,
    STATE(53), 2,
      sym_type_definition_item,
      aux_sym_type_definition_repeat1,
  [1783] = 3,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    STATE(88), 1,
      aux_sym_enumeration_type_repeat1,
  [1793] = 3,
    ACTIONS(282), 1,
      anon_sym_COLON,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym_parameter_item_repeat1,
  [1803] = 3,
    ACTIONS(287), 1,
      anon_sym_ext,
    ACTIONS(289), 1,
      anon_sym_pre,
    STATE(111), 1,
      sym_process_body,
  [1813] = 3,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    ACTIONS(291), 1,
      anon_sym_RBRACE,
    STATE(85), 1,
      aux_sym_map_expression_repeat1,
  [1823] = 2,
    ACTIONS(293), 1,
      sym_identifier,
    STATE(60), 2,
      sym_variable_definition_item,
      aux_sym_variable_definition_repeat1,
  [1831] = 3,
    ACTIONS(295), 1,
      anon_sym_COMMA,
    ACTIONS(298), 1,
      anon_sym_RBRACE,
    STATE(85), 1,
      aux_sym_map_expression_repeat1,
  [1841] = 3,
    ACTIONS(41), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      aux_sym_expression_list_repeat1,
  [1851] = 3,
    ACTIONS(302), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      aux_sym_enumeration_type_repeat1,
  [1861] = 3,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    ACTIONS(307), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      aux_sym_enumeration_type_repeat1,
  [1871] = 3,
    ACTIONS(272), 1,
      sym_identifier,
    ACTIONS(309), 1,
      anon_sym_end,
    STATE(91), 1,
      aux_sym_composite_type_repeat1,
  [1881] = 3,
    ACTIONS(287), 1,
      anon_sym_ext,
    ACTIONS(289), 1,
      anon_sym_pre,
    STATE(110), 1,
      sym_process_body,
  [1891] = 3,
    ACTIONS(311), 1,
      sym_identifier,
    ACTIONS(314), 1,
      anon_sym_end,
    STATE(91), 1,
      aux_sym_composite_type_repeat1,
  [1901] = 3,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    ACTIONS(316), 1,
      anon_sym_COMMA,
    STATE(92), 1,
      aux_sym_expression_list_repeat1,
  [1911] = 1,
    ACTIONS(319), 3,
      anon_sym_pre,
      anon_sym_wr,
      anon_sym_rd,
  [1917] = 3,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(321), 1,
      anon_sym_COLON,
    STATE(81), 1,
      aux_sym_parameter_item_repeat1,
  [1927] = 1,
    ACTIONS(323), 2,
      ts_builtin_sym_end,
      anon_sym_process,
  [1932] = 2,
    ACTIONS(325), 1,
      anon_sym_LT,
    STATE(101), 1,
      sym_enumeration_value,
  [1939] = 2,
    ACTIONS(325), 1,
      anon_sym_LT,
    STATE(80), 1,
      sym_enumeration_value,
  [1946] = 1,
    ACTIONS(327), 2,
      anon_sym_end,
      sym_identifier,
  [1951] = 1,
    ACTIONS(298), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1956] = 1,
    ACTIONS(329), 2,
      ts_builtin_sym_end,
      anon_sym_process,
  [1961] = 1,
    ACTIONS(305), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1966] = 1,
    ACTIONS(331), 2,
      ts_builtin_sym_end,
      anon_sym_process,
  [1971] = 2,
    ACTIONS(252), 1,
      sym_identifier,
    STATE(73), 1,
      sym_parameter_item,
  [1978] = 1,
    ACTIONS(333), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1983] = 1,
    ACTIONS(282), 2,
      anon_sym_COLON,
      anon_sym_COMMA,
  [1988] = 2,
    ACTIONS(335), 1,
      anon_sym_SLASH,
    ACTIONS(337), 1,
      sym__semicolon,
  [1995] = 1,
    ACTIONS(339), 1,
      anon_sym_of,
  [1999] = 1,
    ACTIONS(341), 1,
      sym__semicolon,
  [2003] = 1,
    ACTIONS(343), 1,
      anon_sym_RBRACE,
  [2007] = 1,
    ACTIONS(345), 1,
      anon_sym_end_process,
  [2011] = 1,
    ACTIONS(347), 1,
      anon_sym_end_process,
  [2015] = 1,
    ACTIONS(349), 1,
      sym__semicolon,
  [2019] = 1,
    ACTIONS(351), 1,
      sym__semicolon,
  [2023] = 1,
    ACTIONS(353), 1,
      anon_sym_COLON,
  [2027] = 1,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
  [2031] = 1,
    ACTIONS(355), 1,
      sym_identifier,
  [2035] = 1,
    ACTIONS(357), 1,
      sym_identifier,
  [2039] = 1,
    ACTIONS(359), 1,
      anon_sym_COLON,
  [2043] = 1,
    ACTIONS(361), 1,
      anon_sym_GT,
  [2047] = 1,
    ACTIONS(363), 1,
      sym_identifier,
  [2051] = 1,
    ACTIONS(365), 1,
      anon_sym_end_process,
  [2055] = 1,
    ACTIONS(367), 1,
      anon_sym_to,
  [2059] = 1,
    ACTIONS(369), 1,
      sym_identifier,
  [2063] = 1,
    ACTIONS(371), 1,
      anon_sym_RPAREN,
  [2067] = 1,
    ACTIONS(373), 1,
      sym__semicolon,
  [2071] = 1,
    ACTIONS(375), 1,
      sym__semicolon,
  [2075] = 1,
    ACTIONS(377), 1,
      sym__semicolon,
  [2079] = 1,
    ACTIONS(379), 1,
      anon_sym_of,
  [2083] = 1,
    ACTIONS(381), 1,
      anon_sym_of,
  [2087] = 1,
    ACTIONS(383), 1,
      ts_builtin_sym_end,
  [2091] = 1,
    ACTIONS(385), 1,
      sym__semicolon,
  [2095] = 1,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
  [2099] = 1,
    ACTIONS(387), 1,
      anon_sym_LPAREN,
  [2103] = 1,
    ACTIONS(389), 1,
      anon_sym_COLON,
  [2107] = 1,
    ACTIONS(391), 1,
      anon_sym_EQ,
  [2111] = 1,
    ACTIONS(393), 1,
      sym_identifier,
  [2115] = 1,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
  [2119] = 1,
    ACTIONS(395), 1,
      sym_identifier,
  [2123] = 1,
    ACTIONS(397), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 154,
  [SMALL_STATE(8)] = 184,
  [SMALL_STATE(9)] = 214,
  [SMALL_STATE(10)] = 244,
  [SMALL_STATE(11)] = 274,
  [SMALL_STATE(12)] = 314,
  [SMALL_STATE(13)] = 359,
  [SMALL_STATE(14)] = 389,
  [SMALL_STATE(15)] = 419,
  [SMALL_STATE(16)] = 456,
  [SMALL_STATE(17)] = 487,
  [SMALL_STATE(18)] = 524,
  [SMALL_STATE(19)] = 553,
  [SMALL_STATE(20)] = 590,
  [SMALL_STATE(21)] = 619,
  [SMALL_STATE(22)] = 656,
  [SMALL_STATE(23)] = 685,
  [SMALL_STATE(24)] = 722,
  [SMALL_STATE(25)] = 759,
  [SMALL_STATE(26)] = 796,
  [SMALL_STATE(27)] = 833,
  [SMALL_STATE(28)] = 862,
  [SMALL_STATE(29)] = 891,
  [SMALL_STATE(30)] = 928,
  [SMALL_STATE(31)] = 965,
  [SMALL_STATE(32)] = 1001,
  [SMALL_STATE(33)] = 1034,
  [SMALL_STATE(34)] = 1067,
  [SMALL_STATE(35)] = 1100,
  [SMALL_STATE(36)] = 1133,
  [SMALL_STATE(37)] = 1166,
  [SMALL_STATE(38)] = 1199,
  [SMALL_STATE(39)] = 1232,
  [SMALL_STATE(40)] = 1265,
  [SMALL_STATE(41)] = 1298,
  [SMALL_STATE(42)] = 1331,
  [SMALL_STATE(43)] = 1357,
  [SMALL_STATE(44)] = 1368,
  [SMALL_STATE(45)] = 1379,
  [SMALL_STATE(46)] = 1390,
  [SMALL_STATE(47)] = 1401,
  [SMALL_STATE(48)] = 1412,
  [SMALL_STATE(49)] = 1423,
  [SMALL_STATE(50)] = 1434,
  [SMALL_STATE(51)] = 1445,
  [SMALL_STATE(52)] = 1465,
  [SMALL_STATE(53)] = 1484,
  [SMALL_STATE(54)] = 1499,
  [SMALL_STATE(55)] = 1514,
  [SMALL_STATE(56)] = 1533,
  [SMALL_STATE(57)] = 1547,
  [SMALL_STATE(58)] = 1559,
  [SMALL_STATE(59)] = 1571,
  [SMALL_STATE(60)] = 1583,
  [SMALL_STATE(61)] = 1597,
  [SMALL_STATE(62)] = 1611,
  [SMALL_STATE(63)] = 1623,
  [SMALL_STATE(64)] = 1637,
  [SMALL_STATE(65)] = 1649,
  [SMALL_STATE(66)] = 1658,
  [SMALL_STATE(67)] = 1667,
  [SMALL_STATE(68)] = 1674,
  [SMALL_STATE(69)] = 1685,
  [SMALL_STATE(70)] = 1692,
  [SMALL_STATE(71)] = 1703,
  [SMALL_STATE(72)] = 1716,
  [SMALL_STATE(73)] = 1723,
  [SMALL_STATE(74)] = 1730,
  [SMALL_STATE(75)] = 1737,
  [SMALL_STATE(76)] = 1747,
  [SMALL_STATE(77)] = 1757,
  [SMALL_STATE(78)] = 1765,
  [SMALL_STATE(79)] = 1775,
  [SMALL_STATE(80)] = 1783,
  [SMALL_STATE(81)] = 1793,
  [SMALL_STATE(82)] = 1803,
  [SMALL_STATE(83)] = 1813,
  [SMALL_STATE(84)] = 1823,
  [SMALL_STATE(85)] = 1831,
  [SMALL_STATE(86)] = 1841,
  [SMALL_STATE(87)] = 1851,
  [SMALL_STATE(88)] = 1861,
  [SMALL_STATE(89)] = 1871,
  [SMALL_STATE(90)] = 1881,
  [SMALL_STATE(91)] = 1891,
  [SMALL_STATE(92)] = 1901,
  [SMALL_STATE(93)] = 1911,
  [SMALL_STATE(94)] = 1917,
  [SMALL_STATE(95)] = 1927,
  [SMALL_STATE(96)] = 1932,
  [SMALL_STATE(97)] = 1939,
  [SMALL_STATE(98)] = 1946,
  [SMALL_STATE(99)] = 1951,
  [SMALL_STATE(100)] = 1956,
  [SMALL_STATE(101)] = 1961,
  [SMALL_STATE(102)] = 1966,
  [SMALL_STATE(103)] = 1971,
  [SMALL_STATE(104)] = 1978,
  [SMALL_STATE(105)] = 1983,
  [SMALL_STATE(106)] = 1988,
  [SMALL_STATE(107)] = 1995,
  [SMALL_STATE(108)] = 1999,
  [SMALL_STATE(109)] = 2003,
  [SMALL_STATE(110)] = 2007,
  [SMALL_STATE(111)] = 2011,
  [SMALL_STATE(112)] = 2015,
  [SMALL_STATE(113)] = 2019,
  [SMALL_STATE(114)] = 2023,
  [SMALL_STATE(115)] = 2027,
  [SMALL_STATE(116)] = 2031,
  [SMALL_STATE(117)] = 2035,
  [SMALL_STATE(118)] = 2039,
  [SMALL_STATE(119)] = 2043,
  [SMALL_STATE(120)] = 2047,
  [SMALL_STATE(121)] = 2051,
  [SMALL_STATE(122)] = 2055,
  [SMALL_STATE(123)] = 2059,
  [SMALL_STATE(124)] = 2063,
  [SMALL_STATE(125)] = 2067,
  [SMALL_STATE(126)] = 2071,
  [SMALL_STATE(127)] = 2075,
  [SMALL_STATE(128)] = 2079,
  [SMALL_STATE(129)] = 2083,
  [SMALL_STATE(130)] = 2087,
  [SMALL_STATE(131)] = 2091,
  [SMALL_STATE(132)] = 2095,
  [SMALL_STATE(133)] = 2099,
  [SMALL_STATE(134)] = 2103,
  [SMALL_STATE(135)] = 2107,
  [SMALL_STATE(136)] = 2111,
  [SMALL_STATE(137)] = 2115,
  [SMALL_STATE(138)] = 2119,
  [SMALL_STATE(139)] = 2123,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2),
  [7] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_expression, 2),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_expression, 2),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_expression, 3),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_expression, 3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_expression, 3),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map_expression, 3),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_expression, 4),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map_expression, 4),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_list, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_list_repeat1, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_item, 3),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process_body, 6),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process_body, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_type, 4, .production_id = 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_type, 4, .production_id = 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enumeration_type, 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_type, 3),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 3),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_type, 3),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enumeration_type, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 2),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(135),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_definition_repeat1, 2),
  [197] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_type_definition_repeat1, 2), SHIFT_REPEAT(135),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_type_definition_repeat1, 2),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_process_body_repeat1, 2),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_process_body_repeat1, 2), SHIFT_REPEAT(116),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 2),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_definition_repeat1, 2),
  [227] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_variable_definition_repeat1, 2), SHIFT_REPEAT(134),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_definition_repeat1, 2),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(103),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition_item, 4),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition_item, 4),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_item, 4),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process_definition, 1),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 3, .production_id = 1),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_process_definition_repeat1, 2),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_process_definition_repeat1, 2), SHIFT_REPEAT(138),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 5, .production_id = 1),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_item, 3),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition_item, 4),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_definition_item, 4),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_item_repeat1, 2),
  [284] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_item_repeat1, 2), SHIFT_REPEAT(120),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [295] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_expression_repeat1, 2), SHIFT_REPEAT(31),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_expression_repeat1, 2),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_list, 2),
  [302] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enumeration_type_repeat1, 2), SHIFT_REPEAT(96),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enumeration_type_repeat1, 2),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [309] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [311] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_composite_type_repeat1, 2, .production_id = 4), SHIFT_REPEAT(118),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_composite_type_repeat1, 2, .production_id = 4),
  [316] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_list_repeat1, 2), SHIFT_REPEAT(34),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ext_item, 4),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process_definition_item, 9),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_composite_type_repeat1, 4, .production_id = 5),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process_definition_item, 8),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process_definition_item, 7),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enumeration_value, 3),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [397] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sofl() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
